<a href="https://colab.research.google.com/github/24001616-cyber/data-science-toolkit/blob/library%2Fnumpy/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [2]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [3]:
b=np.random.randint(0,10, size = (3,4)) #integers between 0 and 9
print(b)

[[8 4 1 8]
 [2 2 3 2]
 [4 0 4 1]]


3. Create a numpy array of ones and a numpy array of zeroes

In [8]:
n1=np.ones((1,2))
print(n1)

[[1. 1.]]


In [9]:
n2=np.zeros((2,2))
print(n2)

[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [11]:
c = np.random.randint(0, 10, size=(6, 3))
print("Original array (6x3):")
print(c)

Original array (6x3):
[[3 0 6]
 [2 8 9]
 [9 4 3]
 [9 5 3]
 [6 8 6]
 [3 9 2]]


In [12]:
print("\nTransposed array (3x6):")
print(c.T)


Transposed array (3x6):
[[3 2 9 9 6 3]
 [0 8 4 5 8 9]
 [6 9 3 3 6 2]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [14]:
n, p, m = 4, 5, 3   # example sizes

# Random arrays
d = np.random.randint(0, 10, size=(n, p))   # shape (n, p)
e = np.random.randint(0, 10, size=(p, m))   # shape (p, m)

print("Array d (n x p):")
print(d)
print("\nArray e (p x m):")
print(e)

Array d (n x p):
[[9 9 3 1 1]
 [3 2 1 3 0]
 [2 4 1 1 6]
 [2 0 4 5 6]]

Array e (p x m):
[[1 6 8]
 [2 0 5]
 [0 8 4]
 [9 4 6]
 [2 5 2]]


In [15]:
f = np.dot(d, e)   # or d @ e
print("\nDot product result (n x m):")
print(f)


Dot product result (n x m):
[[ 38  87 137]
 [ 34  38  56]
 [ 31  54  58]
 [ 59  94  74]]
